import '@ssot/date_time_constants.ts';
import {
   check,
   integer,
   minLength,
   minValue,
   maxLength,
   number,
   pipe,
   regex,
   string,
   transform,
   trim,
   union,
} from 'valibot';
import { DateTime } from 'luxon';
import { MIN_LEGAL_AGE } from '@ssot/policy_constants.ts';

const baseStringMaxLength = 128 as const;
const longStringMaxLength = 2056 as const;

export const baseString = pipe(
   string(`Must be a string.`),
   trim(),
   minLength(2, `String should be at least 2 characters long.`),
   maxLength(baseStringMaxLength, `String is too long.`)
);

export const longString = pipe(
   string(`Must be a string.`),
   trim(),
   minLength(2, `String should be at least 2 characters long.`),
   maxLength(longStringMaxLength, `String is too long.`)
);

export const nameString = pipe(
   baseString,
   regex(
      /^[\p{L} .'\-'']+$/u,
      `Must not contain invalid or consecutive non-alphanumeric characters in name.`
   ),
   transform(name => {
      const words = name
         .split(/[\s-]+/)
         .map(w => `${w.slice(0, 1).toUpperCase()}${w.slice(1).toLowerCase()}`);
      const separators = name.match(/[\s-]+/g) ?? [];
      return words.reduce(
         (acc, cur, idx) => acc + cur + (separators[idx] ?? ''),
         ''
      );
   })
);

export const positiveInteger = pipe(
   baseString,
   transform(val => parseInt(val, 10)),
   number(`Must be a number (valibot)`),
   integer(`Must be an integer (valibot)`),
   minValue(1, `Must be a positive integer number (valibot).`)
);

export const objectIdFormatCheck = pipe(
   baseString,
   regex(/^[a-f\d]{24}$/i, `Must be a valid ObjectId format (valibot).`)
);

export const idOrName = union(
   [objectIdFormatCheck, nameString],
   `Must be either an ID or a name`
);

export const dateFromString = pipe(
   baseString,
   regex(
      /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}\.\d{1,3}Z)?$/,
      `Must be in either "YYYY-MM-DD" or "YYYY-MM-DDTHH:mm:ss.sssZ" format (valibot).`
   ),
   check(input => {
      return DateTime.fromISO(input).isValid;
   }, `Must be a valid calendar date (valibot)`)
);

// Used specifically for YYYY-MM-DD dates (10 characters only). E.g., birthdays or expiry dates.
export const dateFromShortString = pipe(
   baseString,
   regex(/^\d{4}-\d{2}-\d{2}$/, `Must be a valid calendar date (YYYY-MM-DD).`),
   check(input => {
      return DateTime.fromISO(input).isValid;
   }, `Invalid date format.`)
);

export const validateExpiryDate = pipe(
   dateFromShortString,
   transform(input => {
      // We give our patients the full benefit of their final day of coverage.
      return DateTime.fromISO(input).endOf('day');
   }),
   check(expiry => {
      return expiry >= DateTime.now();
   }, `The health card has expired.`)
);

export const validateDOB = pipe(
   dateFromShortString,
   transform(input => {
      // Return as a "local" date in Cambridge, ON (which is "America/Toronto", check `date_time_constants.ts`)
      return DateTime.fromISO(input).startOf('day');
   }),
   check(dob => {
      // Compare against "local" now in Cambridge
      const age = DateTime.now().diff(dob, 'years').years;
      return age >= MIN_LEGAL_AGE;
   }, `The patient must be at least ${MIN_LEGAL_AGE} years old (valibot).`),
   check(dob => {
      return dob.year > 1900;
   }, `The patient must be born after 1900 (valibot).`),
   transform(dob => {
      return dob.toISODate(); // Returns simple "YYYY-MM-DD" formatted string.
   })
);

export const dateInThePastOrOptionallyToday = pipe(
   // Accepts both short (YYYY-MM-DD — 10 characters) and long (YYYY-MM-DDTHH:mm:ss.sssZ — 24 characters) date strings.
   dateFromString,

   // Validate against the correct clock while we still have the raw string context.
   check(input => {
      const fromIso = DateTime.fromISO(input);

      if (input.length === 10) {
         /* Date in a distant past. In fact, so distant nobody remembers the exact time the event this date represents happened. Most of the time, these are either legacy dates or manually typed in ones. Short dates are valid for "today". */
         const todayLocal = DateTime.now().startOf('day');
         return fromIso.startOf('day') <= todayLocal;
      } else {
         /* Real-time Timestamp. This kind of timestamps are usually generated by the app itself. */
         return fromIso <= DateTime.now();
      }
   }, `Date cannot be in the future (valibot).`),

   // Now that it's validated, safely transform it into a JavaScript date (UTC-based).
   transform(input => {
      const fromIso = DateTime.fromISO(input);
      const output = input.length === 10 ? fromIso.startOf('day') : fromIso;
      return output.toJSDate();
   })
);

export const dateInTheFutureOrOptionallyToday = pipe(
   // Accepts both short (YYYY-MM-DD — 10 characters) and long (YYYY-MM-DDTHH:mm:ss.sssZ — 24 characters) date strings.
   dateFromString,
   check(input => {
      const fromIso = DateTime.fromISO(input);

      if (input.length === 10) {
         /* Date in the future. And we don't know the exact moment. Valid if "today". */
         const todayLocal = DateTime.now().endOf('day');
         return fromIso.endOf('day') >= todayLocal;
      } else {
         // Real-time Timestamp. Must be the current moment or later.
         return fromIso >= DateTime.now();
      }
   }, `Date cannot be in the past (valibot).`),

   transform(input => {
      const fromIso = DateTime.fromISO(input);
      // For termination boundaries, endOf('day') ensures the date covers the patient until the very last moment of that day.
      const output = input.length === 10 ? fromIso.endOf('day') : fromIso;
      return output.toJSDate();
   })
);

export const validateCanadianPostalCode = pipe(
   baseString,
   regex(
      /^[A-Za-z]\d[A-Za-z][ ]?\d[A-Za-z]\d$/i,
      `Invalid Canadian postal code format (valibot).`
   )
);

export const validateNANPPhoneNumber = pipe(
   baseString,
   transform(phone => phone.replace(/[^\d]/g, '')),
   regex(/^1?[2-9]\d{2}[2-9]\d{6}$/, `Must be an NANP phone number (valibot).`)
);

export const validateDIN = pipe(
   baseString,
   regex(/^\d{8}$/, `DIN must be exactly 8 digits (valibot).`)
);
